import '../styles/globals.scss';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <head>
        <title>Sujeito Pizza</title>
        <meta property="og:title" content="Sujeito Pizza" key="sujeitopizza" />
      </head>
      <body>{children}</body>
    </html>
  )
}
